try{console.log("Hello Ease.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
function prettyDate(b){var b=new Date((b||"").replace(/-/g,"/").replace(/[TZ]/g," ")),b=((new Date).getTime()-b.getTime()+(b.getTimezoneOffset()+60)*6E4)/1E3,a=Math.floor(b/86400);return isNaN(a)||a<0||a>=31?void 0:a==0&&(b<60&&"just now"||b<120&&"1 minute ago"||b<3600&&Math.floor(b/60)+" minutes ago"||b<7200&&"1 hour ago"||b<86400&&Math.floor(b/3600)+" hours ago")||a==1&&"Yesterday"||a<7&&a+" days ago"||a<31&&Math.ceil(a/7)+" weeks ago"}var Ease=Ease||{};
(function(b){Ease.setDefaults=function(a){if(this.defaults)for(var b in this.defaults)this[b]=a[b]||this.defaults[b];delete this.defaults};Ease.MONTHS="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");Ease.formatDate=function(a){a=a.split("-");a=new Date(a[0],a[1],a[2]);return a=""+Ease.MONTHS[a.getMonth()]+" "+(a.getDay()+1)+", "+a.getFullYear()};Ease.BitFeed=function(a){this.defaults={url:null,id:null,contSelector:null};Ease.setDefaults.apply(this,[a]);this.$cont=b(this.contSelector);
if(!this.$cont.length)return!1;this._feed_data=this.ajax=null;this.itemIndex={};this.items=[];this.currentItem=null;return this.init()};Ease.BitFeed.prototype={init:function(){this.$header=b("#list-head");this.$footer=b("#list-foot");this.$listCont=b("#list-cont");this.$leafCont=b("#leaf-cont");this.$listInfo=b("#list-info");this.$leaf=this.makeLeaf().prependTo(this.$leafCont);this.fetchFeed();this.fixFlex()},fixFlex:function(){var a=this,d=b(window),c=!1;b(window).scroll(function(){d.scrollTop()>
0&&!c?(c=!0,a.$listInfo.css({position:"fixed",left:a.$cont.position().left-20})):c||(a.$listInfo.css({position:"absolute",left:0}),c=!1)}).resize(function(){c&&(a.$listInfo.css({left:a.$cont.position().left-20}),a.$leafCont.height(b(this).height()+2))});d.trigger("resize").trigger("scroll")},fetchFeed:function(){var a=this;this.ajax=b.ajax(this.url,{dataType:"jsonp",data:{_id:this.id,_render:"json"},jsonp:"_callback",success:function(b,c,e){a.processFeed.apply(a,arguments)}})},processFeed:function(a,
d){this.$listCont.html("");this.$list=null;b("#loading").hide();if(d==="success"&&a.value.items.length)this._feed_data=a.value.items[0],this.makeListHeader(),this.makeList(),this.makeListFooter()},makeListHeader:function(){this.$header.html("");var a=this._feed_data,d=b("<h1 />",{html:'<span class="text">'+a.title.content+"<span>"}).appendTo(this.$header);a.icon&&b("<div />",{html:'<img src="'+a.logo+'" alt="'+a.title.content+'" />'}).addClass("icon").prependTo(d);a.updated&&b("<div />",{text:"Updated "+
prettyDate(a.updated)}).addClass("date").appendTo(this.$header)},makeListFooter:function(){this.$footer.html("");var a=this._feed_data;a.rights&&a.rights.content&&b("<div />",{text:a.title.content+" - "+a.rights.content}).addClass("copy").appendTo(this.$footer)},makeList:function(){if(!this.$list)this.$list=b("<div />",{}).addClass("list-list").appendTo(this.$listCont);var a=this,d=function(){return a.onListClick(this.id)};b.each(this._feed_data.entry,function(){var b=new Ease.BitFeed.Item(a,this);
b.$item.click(d).appendTo(a.$list);a.itemIndex[this.id]=a.items.push(b)-1})},onListClick:function(a){this.currentItem=this.getItemById(a);this.updateLeaf()},onLeafBack:function(){this.currentItem=null;this.$leafCont.css({left:"-9999em"})},onLeafNext:function(){if(!this.currentItem)return!1;var a=this.getItemIndex(this.currentItem.data.id)+1;a>=this.items.length&&(a=0);this.currentItem=this.getItemByIndex(a);return this.updateLeaf()},onLeafPrev:function(){if(!this.currentItem)return!1;var a=this.getItemIndex(this.currentItem.data.id)-
1;a<0&&(a=this.items.length-1);this.currentItem=this.getItemByIndex(a);return this.updateLeaf()},getItemIndex:function(a){return this.itemIndex[a]},getItemByIndex:function(a){return this.items[a]},getItemById:function(a){return this.getItemByIndex(this.getItemIndex(a))},updateLeaf:function(){this.$leaf.find("article").html(this.currentItem.buildLeafContent());this.$leafCont.css({left:0})},makeLeaf:function(){var a=this,d=b("<div />",{id:"leaf",html:'<div class="span8 wrap"><article></article></div>'}).addClass("container");
b("<button />",{id:"leaf-back",text:"Back to list"}).addClass("btn btn-leaf-back").click(function(){a.onLeafBack.call(a)}).prependTo(d.find(".wrap"));var c=b("<div />",{id:"leaf-nav"}).prependTo(d.find(".wrap"));b("<button />",{text:"Previous"}).addClass("btn btn-prev").click(function(){a.onLeafPrev.call(a)}).appendTo(c);b("<button />",{text:"Next"}).addClass("btn btn-next").click(function(){a.onLeafNext.call(a)}).appendTo(c);return d}};Ease.BitFeed.Item=function(a,b){this._feed=a;this.data=b;this.$full_content=
this.$item=null;this.init();return this};Ease.BitFeed.Item.prototype={init:function(){this.$item=b("<article />",{id:this.data.id}).addClass("list-item");this.$full_content=b("<div />",{html:this.data.content.content}).addClass("content");this.buildListContent()},buildListContent:function(){this.makeItemHeader().appendTo(this.$item);this.makeDate(!0).appendTo(this.$item);b("<div />",{text:this.getShortContent(140,!0)}).addClass("content").appendTo(this.$item)},makeItemHeader:function(){var a=b("<header />",
{html:'<span class="pic"><span class="line"></span></span><span class="text">'+this.data.title+"</span>"}).addClass("item-head");a.find(".pic").append(this.makeThumbnail());return a},makeThumbnail:function(){var a=new Image,b=this;a.onerror=function(){this.src=b._feed._feed_data.icon};a.src=this.data["media:thumbnail"].url;return a},makeDate:function(a){var d=this.data.published;d=a?(d=prettyDate(this.data.published))?d:Ease.formatDate(this.data.published):Ease.formatDate(d);return b("<span />",{text:"Added "+
d}).addClass("time")},makeItemFormat:function(){var a=b("<ul />");if(this.data.format){var d=!1,c;for(c in this.data.format){var e=this.data.format[c];e&&c!=="xmlns"&&(d='<li><span class="label">'+c.replace("_"," ").replace("_"," ")+':</span><span class="value">'+e+"</span></li>",a.append(d),d=!0)}d&&a.addClass("well item-format")}return a},makeAuthor:function(){return b("<span />",{text:this.data.author&&this.data.author.name?this.data.author.name:""}).addClass("author")},makeLinks:function(){var a=
this,d=b("<div />",{}).addClass("links");b.each(this.data.link,function(){var c="link";switch(this.rel){case "alternate":c="More Information";break;case "enclosure":c="Download Torrent";break;case "license":c=a.data.rights}b("<a />",{text:c,href:this.href,rel:this.rel,type:this.type?this.type:"",target:"_blank"}).appendTo(d)});return d},buildLeafContent:function(){var a=b("<div />").addClass("leaf-content");this.makeItemHeader().appendTo(a);this.makeItemFormat().appendTo(a);this.makeAuthor().appendTo(a);
this.makeDate().appendTo(a);this.makeLinks().appendTo(a);this.$full_content.appendTo(a);return a},getShortContent:function(a,b){var c=this.$full_content.text(),e=c.length>a,c=e?c.substr(0,a-1):c,c=e&&b?c.substr(0,c.lastIndexOf(" ")):c;return e?c+"...":c}}})(jQuery);(function(b){b(document).ready(function(){new Ease.BitFeed({url:"http://pipes.yahoo.com/pipes/pipe.run",id:"f42c711ab0e64056fd200b38ad98e102",contSelector:"#feed"})})})(jQuery);
